version: '3.8'
services:
  service-api:
    build: .
    env_file: .env
    ports: 
      - 8080:8080
      - 9000:9000
    image: registry.punk.link/service-api:latest
    healthcheck:
      test: curl --fail http://127.0.0.1/health || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s