FROM golang:alpine AS builder

ARG GO_ENVIRONMENT
ARG LOG_LEVEL
ARG DB_HOST
ARG DB_PORT
ARG DB_USERNAME
ARG DB_PASSWORD
ARG GIN_ADDR
ARG GIN_PORT
ARG SPOTIFY_CLIENT_ID
ARG SPOTIFY_CLIENT_SECRET

ENV GO_ENVIRONMENT=$GO_ENVIRONMENT
ENV LOG_LEVEL=$LOG_LEVEL
ENV DB_HOST=$DB_HOST
ENV DB_PORT=$DB_PORT
ENV DB_USERNAME=$DB_USERNAME
ENV DB_PASSWORD=$DB_PASSWORD
ENV GIN_ADDR=$GIN_ADDR
ENV GIN_PORT=$GIN_PORT
ENV SPOTIFY_CLIENT_ID=$SPOTIFY_CLIENT_ID
ENV SPOTIFY_CLIENT_SECRET=$SPOTIFY_CLIENT_SECRET

WORKDIR /

ADD go.mod .

COPY . .

RUN go build -o bin/service-api.exe -ldflags="-s -w"

FROM alpine

WORKDIR /

COPY --from=builder /bin .

EXPOSE 8080

CMD ["./service-api.exe"]